### ISSUE TITLE
离线版文档

### ISSUE THREAD

**Issue by duohappy** [waruqi/xmake-docs#9]
请问是否可以提供xmake帮助的离线版文档呢？

**Comment by waruqi** [comment]
里面就几个md，你直接下载下来用vscode md preview看就好，或者转成pdf

**Comment by duohappy** [comment]
> 
> 
> 里面就几个md，你直接下载下来用vscode md preview看就好，或者转成pdf

嗯嗯，这个我懂的:smile:。我只是觉得官方离线帮助文档很重要，用户很可能需要这份文档，提供官方帮助文档，会方便用户一点。

**Comment by waruqi** [comment]
目前没时间单独维护离线，你可以自己稍微转下 pdf  不过 dash app for macos 有人家帮忙维护的离线文档
